### PR TITLE
Added logic that converts full year into a short year variable

### PR DESCRIPTION
**Pull request by schalkventer**
Added the following code block where needed as an ad-hoc solution: 

```
{% if page.financial_year == '2015-16' %}
  {% assign shortYear = '2015' %}
{% elsif page.financial_year == '2016-17' %}
  {% assign shortYear = '2016' %}
{% elsif page.financial_year == '2017-18' %}
  {% assign shortYear = '2017' %}
{% elsif page.financial_year == '2018-19' %}
  {% assign shortYear = '2018' %}
{% else %}
  {% assign shortYear = page.financial_year %}
{% endif %}
```

### CODE REVIEW

**Comment by longhotsummer** [comment]
Would this be easier `page.financial_year | split: "-" | first`?

**Comment by longhotsummer** [comment]
On second thoughts, can you pls keep the 2017-18 in `Where national govt gets...` and `How govt spends...`. 

We're going to have to consider these changes more carefully after this.

**Comment by schalkventer** [comment]
Thanks for the filter above, @longhotsummer. Looks great! I'm not that experience with Jekyll's filters.

**Comment by schalkventer** [comment]
revised

**Pull request merged**
