### PR TITLE
Incorporates the contributed dataset pages into the design system

### PR DESCRIPTION
**Pull request by schalkventer**
screencapture-localhost-4000-datasets-mud-to-bricks-a-review-of-school-infrastructure-spending-and-delivery-2018-03-12-19_08_59

### CODE REVIEW

**Comment by longhotsummer** [comment]
I like that this design puts the dataset downloads beneath the dataset description in the main column.

**Comment by schalkventer** [comment]
@longhotsummer, how about this solution for now?

screencapture-localhost-4000-datasets-mud-to-bricks-a-review-of-school-infrastructure-spending-and-delivery-2018-03-13-08_23_39

**Comment by schalkventer** [comment]
Further changed to the following: 
image

**Comment by schalkventer** [comment]
Opened a new PR.

**Pull request closed without merging**
