### PR TITLE
 Creates mechanism to download SVG Charts as PNG all the way down to IE10

### PR DESCRIPTION
**Pull request by schalkventer**

### CODE REVIEW

**Comment by schalkventer** [comment]
screenshot

download

**Comment by schalkventer** [comment]
Download options are small (current size), medium (x2), large (x3).

**Comment by jbothma** [comment]
Out of interest, why are we going away from this as the format selector? https://app.zeplin.io/project/5a686e1f6fe15f182537c7d3/screen/5a78819c6b3db26aae9e5c4f

In my mind, we'd provide options like
- Image (PNG Large)
- Image (PNG Medium)
- Image (PNG Small)
- Link _(this would be a link to an anchor for the container)_
- Data (Excel CSV) _(this is a separate feature you don't need to add now, but can be done client-side)_

I like the idea of the widget because it's very flexible so it can set up a pattern used in a lot of places on the site.

**Comment by schalkventer** [comment]
@jbothma I was just in the interest of time, since we already have a dropdown component and button component, however I'm definitely open to standardizing into a single component like above at one point,

Link is a good idea, will add.

**Comment by schalkventer** [comment]
image

**Pull request merged**
