### PR TITLE
Adds redirect link to newsletter sign up button

### PR DESCRIPTION
**Pull request by schalkventer**

### CODE REVIEW

**Comment by jbothma** [comment]
LGTM but can we have a screenshot?

**Comment by longhotsummer** [comment]
@schalkventer screenshot please.

**Comment by longhotsummer** [comment]
Chrome: south african national budget 2017-18 - vulekamali 2018-02-16 11-03-34

**Comment by schalkventer** [comment]
capture

@greg Alignment issue fixed.

**Comment by jbothma** [comment]
signup button label is off-vertical-centre but if it works it's worth merging and coming back to the small cosmetic issue.

**Comment by longhotsummer** [comment]
I still see a wrapped e.

change `.Button` padding to `8px 13px 11px 13px` works for me. That also makes left and right padding equal.

**Comment by longhotsummer** [comment]
I *think* my CSS is up to date, I have checked it out as-is and not run npm build.

**Comment by schalkventer** [comment]
@longhotsummer Wrapping issue should now be resolved.

**Comment by longhotsummer** [comment]
Looks good.

**Pull request merged**
